services:
  app:
    image: ghcr.io/holgerengels/synx:latest
    container_name: synx_app
    expose:
      - "3001"
    volumes:
      - ./config:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongo
    restart: always

  caddy:
    image: caddy:latest
    container_name: synx_caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
      - ./config:/config
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    restart: always

  mongo:
    image: mongo:latest
    container_name: synx_mongo
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
  caddy_data:
  caddy_config:
