import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching'
import { NavigationRoute, registerRoute } from 'workbox-routing'
import { clientsClaim } from 'workbox-core'

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || [])

// Serve cached index.html for all navigation requests (SPA deep links)
const handler = createHandlerBoundToURL('/index.html')
const navigationRoute = new NavigationRoute(handler)
registerRoute(navigationRoute)

// Activate new SW immediately
self.addEventListener('install', () => self.skipWaiting())
clientsClaim()

self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting()
    }
})
